#!/bin/bash
# 
# A keychain-like random password generator
# 
# https://github.com/gidcs/random-password/
# 

function format_v1 {
    _in=$1
    _out=`echo ${_in} | fold -w 1 | awk '
BEGIN{
    cnt=1
}
{
    printf($1)
    if(cnt%3==0){
        printf("-")
    }
    cnt++
}
'`
    echo "${_out::15}"
}

rand=`LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 12 | head -n 1`

echo "Password: ${rand} or `format_v1 ${rand}`"
